### ISSUE TITLE
CORS Backend

### ISSUE THREAD

**Issue by MasterofDragons** [arnaugarcia/sallefy#123]
Enabling CORS backend per peticions des de origins diferents al backend

No s'ha configurat cap domini per tant s'aplica el predeterminat, que haurien de ser els següents according to :

- [https://ionicframework.com/docs/faq/cors#a-enabling-cors-in-a-server-you-control](url)

**Comment by arnaugarcia** [comment]
Perfecte @MasterofDragons ! T'ho miro de fer pel Divendres com a molt tard. T'aviso per aqui :D

**Comment by MasterofDragons** [comment]
He vist que has habilitat el CORS per Production Environment, però encara així em segueix sense permetre connectar-me. La App està s'està executant en un servidor de producció, nose si m'haig de connectar a la API versió producció o com?

![image](https://user-images.githubusercontent.com/37770349/75044460-f8559100-54c1-11ea-819d-39bbb506ac77.png)

**Comment by arnaugarcia** [comment]
Bones, perdona que no t'ho he dit. Prova amb [PRE](http://sallefy-pre.eu-west-3.elasticbeanstalk.com/).

**Comment by arnaugarcia** [comment]
He estat provant i sembla que va bé 🎉 🎉 🎉 
```
curl -I -X OPTIONS \
  -H "Origin: localhost" \
  -H 'Access-Control-Request-Method: GET' \
  http://sallefy-pre.eu-west-3.elasticbeanstalk.com/api/genres 2>&1 | grep 'Access-Control-Allow-Origin'
```

**Comment by MasterofDragons** [comment]
Crec que ja funciona bé, moltíssimes gràcies!

**Comment by arnaugarcia** [comment]
Doncs tanco la issue quelcom hem dius :D
