### ISSUE TITLE
Request songs liked by an user

### ISSUE THREAD

**Issue by MasterofDragons** [arnaugarcia/sallefy#132]
La PUT request al següent endpoint: /me/tracks/liked que teòricament ha de retornar les cançons que un usuari li ha donat like no funciona.

Primerament s'ha fet un toogle a LIKE a una cançó:
![image](https://user-images.githubusercontent.com/37770349/75661071-ec5d9200-5c6c-11ea-92bb-fc2baa57c04a.png)
La imatge mostra que la cançó amb ID: 2 està liked per l'usuari

Llavors es procedeix a demanar totes les cançons likejats pel mateix user:
![image](https://user-images.githubusercontent.com/37770349/75661248-42cad080-5c6d-11ea-93be-f4c5c4ec479f.png)
Com es pot apreciar només em retorna el track liked per defecte

**Comment by arnaugarcia** [comment]
Hmmmmm. Li dono un cop d'ull quan pugi, intentaré arreglar-ho el cap de setmana. Gràcies per reportar-ho.

**Comment by arnaugarcia** [comment]
Hey! Ja he corregit el bug 🎉 Ho he provat i sembla que va bé. Gràcies per reportar el bug i fer l'aplicació millor, si trobes algun més diga'm-ho! :D
