### ISSUE TITLE
Use MAILGUN to send emails if AWS is not activated.

### ISSUE THREAD

**Issue by dribbadev** [arnaugarcia/sallefy#144]
Check https://www.mailgun.com/ for sending emails from the API.

**Comment by arnaugarcia** [comment]
Hi Alex! I was talking with @alfredorueda and we're going to hide the endpoints for resetting password due to Mailgun isn't free :( 
It'll be great to have emails but I think that the better way to do this is creating an email account inside of La Salle infrastructure.
