### ISSUE TITLE
Añadir en Track-Resource GET /api/tracks si usuario que realiza llamada ha dado like o no

### ISSUE THREAD

**Issue by Marcpf96** [arnaugarcia/sallefy#155]
Tal como explica el título sería genial si se pudiera contar con que la llamada principal de obtener tracks pudiera llevar incluido el boolean de si el usuario que realiza la llamada le ha dado like o no a la canción.
De esta manera no tendríamos que hacer tantas consultas como canciones mostremos en una lista, haciendo una llamada general ya nos guardáramos en el objeto track si tiene like o no.
Para cualquier duda respecto a la petición estoy disponible en el correo marc.peligros@salle.url.edu.
Un saludo,

**Comment by arnaugarcia** [comment]
Hola @Marcpf96 ! Se podría hacer perfectamente lo que me da miedo es el tema del performance de la aplicación. Si no representa mucho coste lo implementaré. Lo estoy revisando ahora mismo te dio algo a ver que puede representar.
Gracias por la mejora!

**Comment by arnaugarcia** [comment]
Hola @Marcpf96 se esta subiendo a PRO la versión que me has pedido. Cuando esté online aviso.

**Comment by arnaugarcia** [comment]
Done!

**Comment by alfredorueda** [comment]
Thanks! Good job! :)
