### ISSUE TITLE
Añadir url de Imagen Generica 

### ISSUE THREAD

**Issue by axelinter** [arnaugarcia/sallefy#158]
Controlar las Canciones y las Playlist que no tengan imagen introducida y se envie en su lugar una url genérica de una silueta de un disco o similar.

**Comment by arnaugarcia** [comment]
Hey! Me parece genial la propuesta. De hecho hay un desarrollo local que lo subiré en cuanto pueda que realiza la misma función de Spotify para las playlists. Si hay tracks con "thumbnail", te hará un collage con las carátulas. Sobre el tema de la canciones sin thumbnail eso ya es más complicado por que creo que esto debería ser responsabilidad el front, no del backend.

CC: @alfredorueda

**Comment by alfredorueda** [comment]
Efectivamente, el front-end puede escoger una foto "plantilla" en el caso de que la track no tenga thumbnail.

**Comment by arnaugarcia** [comment]
El patrón a hablado. Cierro la issue y abro una para el tema del collage.
