### ISSUE TITLE
Añadir "genre" como parametro de búsqueda del GET /api/tracks

### ISSUE THREAD

**Issue by Marcpf96** [arnaugarcia/sallefy#172]
Tal como indica el título estaría genial el hecho de disponer de un quinto campo (si contamos con el size) para poder filtrar las canciones, pudiendo filtrarlas por género (String mismo ya vale), nos posibilitaría el poder crear algunos menús mas interesantes para el usuario, como un sistema de recomendaciones basado en los generos que mas escuchas o que mas te han gustado.
![2020-04-14 19_35_14-API](https://user-images.githubusercontent.com/48526974/79255730-179be980-7e87-11ea-8d27-80b617fc9143.png)

Para cualquier duda al respecto estoy disponible en el correo marc.peligros@salle.url.edu

Un saludo,

**Comment by arnaugarcia** [comment]
LGTM! Lo prepararé para el siguiente Sprint.

**Comment by arnaugarcia** [comment]
Hey! ya he acabado el desarrollo pero hay un problema :( Hasta mañana no puedo subir lo ya que estamos "dockerizando" la aplicación y hoy los del grado internacional harán clase así que para no correr riesgos lo subiré entre mañana y el finde. :P 
De todas formas cuando esté os aviso por aquí :D

**Comment by Marcpf96** [comment]
oki, sin problemas, muchas gracias por la rapidez.

**Comment by arnaugarcia** [comment]
Hey! Esta en PRO el cambio. Cierro issue. Si hace falta algo más me dices :D
