### ISSUE TITLE
User Followers & Following

### ISSUE THREAD

**Issue by JiahuiChen99** [arnaugarcia/sallefy#180]
Actualment només està disponible demanar els followers i els following del nostre propi usuari logged in, però no podem demanar els followers & following d'un user en específic. Es podria fer al front-end mitjançant la crida de getAllUsers i mirar si el nostre user fa follow o no i mostrar depenent d'aquest paràmetre, però no em sembla bona pràctica i a més deteriora el rendiment.

Moltes gràcies

**Comment by JiahuiChen99** [comment]
Bones de nou,
També podries ampliar el ventall d'informació que es recupera del endpoint me/followers o me/following (també en el que t'he comentat a l'anterior paràgraf), m'agradaria tenir informació sobre la quantitat de followers d'aquest user, songs, playlist per exemple, com si fos un GET /users

**Comment by arnaugarcia** [comment]
Hey! Sobre l'últim comentari l'han demanat per aquí #176. La tinc implementada i l'intentaré pujar quan pugi :D (l'únic que amb totes les entregues que tenim no puc dedicar tant de temps com abans :( ). Sobre el primer comentari tens tota la raó, estaria bé tindre l'endpoint per recuperar els seguidors i demés, així que intentaré fer-ho també.
Gràcies!

**Comment by JiahuiChen99** [comment]
Entesos, moltíssimes gràcies, en espera dels futurs canvis! :)

**Comment by HobJob** [comment]
El nostre grup també vol fer servir aquests endpoints!

**Comment by HobJob** [comment]
@alfredorueda @arnaugarcia Creieu que pot estar fet per abans de l'entrega?

**Comment by arnaugarcia** [comment]
Hola @HobJob i @JiahuiChen99 he generat la versió ara mateix, ara falta que el Jenkins pugi la versió al cloud. Quan estigui us aviso per aqui!

**Comment by arnaugarcia** [comment]
Yep! Ja la teniu online.
PD: Sorry per tardar tant però tinc moltíssimes trameses de la universitat per acabar encara :P
Si necessiteu alguna cosa més, ja em dieu.
Gràcies!

**Comment by JiahuiChen99** [comment]
Gràcies a tu @arnaugarcia !

**Comment by alfredorueda** [comment]
> Yep! Ja la teniu online.
> PD: Sorry per tardar tant però tinc moltíssimes trameses de la universitat per acabar encara :P
> Si necessiteu alguna cosa més, ja em dieu.
> Gràcies!

Gracias!!! :)
