### ISSUE TITLE
Activate users when they get registered (instead of requiring activation by email)

### ISSUE THREAD

**Issue by alfredorueda** [arnaugarcia/sallefy#23]
Example:

https://github.com/alfredorueda/social-network-backend/blob/master/src/main/java/edu/socialnetwork/service/UserService.java#L121

**Comment by arnaugarcia** [comment]
And disallow that a user can register with ROLE_ADMIN <-- Dangerous

**Comment by arnaugarcia** [comment]
Done!

**Comment by arnaugarcia** [comment]
Available since [0.0.6-SNAPSHOT](https://github.com/arnaugarcia/sallefy/releases/tag/0.0.6-SNAPSHOT)
