### ISSUE TITLE
Create urlPicture field for entities that we want to showcase a Photo

### ISSUE THREAD

**Issue by alfredorueda** [arnaugarcia/sallefy#62]
For example, Playlist or Track. Let's discuss that

**Comment by arnaugarcia** [comment]
We have this already, right?
User: 
https://github.com/arnaugarcia/sallefy/blob/master/src/main/java/com/sallefy/domain/User.java#L84

Playlist:
https://github.com/arnaugarcia/sallefy/blob/master/src/main/java/com/sallefy/domain/Playlist.java#L65
https://github.com/arnaugarcia/sallefy/blob/master/src/main/java/com/sallefy/domain/Playlist.java#L68

Track:
https://github.com/arnaugarcia/sallefy/blob/master/src/main/java/com/sallefy/domain/Track.java#L52
