### ISSUE TITLE
Add email validation

### ISSUE THREAD

**Issue by arnaugarcia** [arnaugarcia/sallefy#69]
All the emails should implement validation to contain the domain of salle.url.edu

**Comment by arnaugarcia** [comment]
@alfredorueda añado la validación del email? si es así, sobre que dominio @students.salle.url.edu? @salle.url.edu?  @salleurl.edu?

**Comment by alfredorueda** [comment]
En parte me parece muy bien, pero por otra parte, me hace gracia que los
alumnos animen a sus familiares y amigos a utilizar su App.

En principio, lo dejamos abierto! ;-)
-- 

Alfredo Rueda Unsain

linkedin.com/in/alfredorueda

**Comment by arnaugarcia** [comment]
Genial, la cierro pues.
