### ISSUE TITLE
PublicAccessible always NULL

### ISSUE THREAD

**Issue by JCarri14** [arnaugarcia/sallefy#80]

**Comment by arnaugarcia** [comment]
Ey!

M'he mirat el tema i resulta que no "hi havia un bug" sinó que l'objecte que s'havia d'enviar era un "PlaylistRequest" no una "Playlist" (els objectes són similars, però un serveix per crear/actualitzar i l'altre és la playlist en si).

El tema està que l'atribut per crear/actualitzar una playlist (PlaylistRequest) es diu "publicAccessible" i no "public" com al de "Playlist" per això sempre era null, ja que el back si detecta un camp que no coneix l'ignora. 

Dit això, he simplificat el tema i tots els objectes sempre tindran el camp "publicAccessible" en comptes de "public"... crec que serà millor, ja que no és una paraula reservada :P

A la pròxima release sortirà. Deixo oberta la issue per relacionar-la amb la pujada i saber quan està PRO perquè puguis validar.

Salut!

**Comment by JCarri14** [comment]
Ep Arnau!

D’acord! Un cop amb la nova release faré les proves!

Seguim amb contacte!

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Arnau Garcia<mailto:notifications@github.com>
Enviado: miércoles, 18 de diciembre de 2019 12:09
Para: arnaugarcia/sallefy<mailto:sallefy@noreply.github.com>
CC: Joan Carrión Anaya<mailto:j.carrion@students.salle.url.edu>; Author<mailto:author@noreply.github.com>
Asunto: Re: [arnaugarcia/sallefy] PublicAccessible always NULL (#80)


Ey!

M'he mirat el tema i resulta que no "hi havia un bug" sinó que l'objecte que s'havia d'enviar era un "PlaylistRequest" no una "Playlist" (els objectes són similars, però un serveix per crear/actualitzar i l'altre és la playlist en si).

El tema està que l'atribut per crear/actualitzar una playlist (PlaylistRequest) es diu "publicAccessible" i no "public" com al de "Playlist" per això sempre era null, ja que el back si detecta un camp que no coneix l'ignora.

Dit això, he simplificat el tema i tots els objectes sempre tindran el camp "publicAccessible" en comptes de "public"... crec que serà millor, ja que no és una paraula reservada :P

A la pròxima release sortirà. Deixo oberta la issue per relacionar-la amb la pujada i saber quan està PRO perquè puguis validar.

Salut!

**Comment by arnaugarcia** [comment]
Ja está a PRO. Valida'm que funcioni i la tanco :D

**Comment by arnaugarcia** [comment]
L'he estat provant i sembla que va bé. Si no fos així o veus quelcom erroni obra'm un altre :D
